name: Deploy Websites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH Key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy Website 1 to EC2
      env:
        EC2_PUBLIC_IP_1: ${{ secrets.EC2_PUBLIC_IP_1 }}
      run: |
        # Securely transfer website1 files to EC2
        scp -i private_key.pem -o StrictHostKeyChecking=no -r website1/* ec2-user@$EC2_PUBLIC_IP_1:/home/ec2-user/
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP_1 <<EOF
          sudo rm -rf /usr/share/nginx/html/*
          sudo mv /home/ec2-user/* /usr/share/nginx/html/
          sudo systemctl restart nginx
        EOF

    - name: Deploy Website 2 to EC2
      env:
        EC2_PUBLIC_IP_2: ${{ secrets.EC2_PUBLIC_IP_2 }}
      run: |
        scp -i private_key.pem -o StrictHostKeyChecking=no -r website2/* ec2-user@$EC2_PUBLIC_IP_2:/home/ec2-user/
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP_2 <<EOF
          sudo rm -rf /usr/share/nginx/html/*
          sudo mv /home/ec2-user/* /usr/share/nginx/html/
          sudo systemctl restart nginx
        EOF
